SET SERVEROUTPUT ON SIZE 100000

DECLARE
  MATCH_COUNT INTEGER;
BEGIN  
  FOR T IN (SELECT OWNER, TABLE_NAME, COLUMN_NAME FROM ALL_TAB_COLUMNS WHERE DATA_TYPE IN ('CHAR', 'VARCHAR2', 'NCHAR', 'NVARCHAR2', 'CLOB', 'NCLOB') AND OWNER = '<SCHEMA_NAME>') 
  LOOP   
    BEGIN
      EXECUTE IMMEDIATE    
        'SELECT COUNT(*) FROM ' || T.OWNER || '.' || T.TABLE_NAME || ' WHERE REGEXP_LIKE ('||T.COLUMN_NAME||', UNISTR(''[\D800-\DFFF]''))'
         INTO MATCH_COUNT;  
      IF MATCH_COUNT > 0 THEN 
        DBMS_OUTPUT.PUT_LINE( T.OWNER || '.' || T.TABLE_NAME ||' '||T.COLUMN_NAME||' '||MATCH_COUNT );
      END IF; 
    EXCEPTION
      WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE( 'ERROR ENCOUNTERED TRYING TO READ ' || T.COLUMN_NAME || ' FROM ' || T.OWNER || '.' || T.TABLE_NAME );
    END;
  END LOOP;
END;